export const searchData = [
  {
    id: 1,
    title: "AI-Powered Enterprise Search",
    description: "Build intelligent search experiences with semantic understanding, dynamic relevance scoring, and trusted source blending.",
    snippet: "Leverage AI to surface insights from documents, knowledge bases, and product catalogs.",
    source: "Open Research Lab",
    category: "AI Strategy",
    tags: ["semantic search", "knowledge graph", "enterprise"],
    url: "https://example.com/insights/enterprise-search",
    rating: 4.9,
    relevance: 98,
    content: "Modern professional search systems require semantic ranking, contextual relevance, and real-time filtering across multiple content types."
  },
  {
    id: 2,
    title: "UX Design Principles for Search",
    description: "Design a search interface that guides users with contextual prompts, relevance hints, and clean results layout.",
    snippet: "Use progressive disclosure and adaptive suggestions to reduce cognitive load.",
    source: "UX Collective",
    category: "Design",
    tags: ["ux", "search", "interaction design"],
    url: "https://example.com/guide/search-ux",
    rating: 4.8,
    relevance: 92,
    content: "A great search engine pairs AI relevance with clear visual hierarchy, fast feedback, and robust filtering controls."
  },
  {
    id: 3,
    title: "Advanced Query Understanding",
    description: "Parse intent, detect entities, and expand search queries with AI to improve result accuracy.",
    snippet: "Make search more powerful by understanding context and user goals.",
    source: "Data Science Weekly",
    category: "Search Tech",
    tags: ["nlp", "query parsing", "intent"],
    url: "https://example.com/tech/advanced-query",
    rating: 4.7,
    relevance: 94,
    content: "Semantic query understanding allows search to map natural language to structured matches, boosting precision."
  },
  {
    id: 4,
    title: "Security and Search Privacy",
    description: "Deliver secure search experiences with encrypted indexing, access controls, and compliance-aware data handling.",
    snippet: "Protect user data and maintain trust across enterprise search deployments.",
    source: "Security Today",
    category: "Security",
    tags: ["privacy", "security", "compliance"],
    url: "https://example.com/security/search-privacy",
    rating: 4.6,
    relevance: 89,
    content: "Advanced search platforms must balance performance with data protection, using role-based access and audit logging."
  },
  {
    id: 5,
    title: "Productivity with Smart Search",
    description: "Use search as a productivity tool by offering saved searches, intelligent recommendations, and context-aware shortcuts.",
    snippet: "Make your search engine a workspace assistant.",
    source: "Productivity Lab",
    category: "Productivity",
    tags: ["recommendations", "workflow", "search"],
    url: "https://example.com/productivity/smart-search",
    rating: 4.85,
    relevance: 95,
    content: "Search can empower teams by combining fast retrieval with actionable next steps and entity extraction."
  },
  {
    id: 6,
    title: "Machine Learning for Search Ranking",
    description: "Implement ML models to learn from user interactions and improve search result relevance over time.",
    snippet: "Use click-through rates and dwell time to train better ranking algorithms.",
    source: "AI Research Journal",
    category: "AI Strategy",
    tags: ["machine learning", "ranking", "personalization"],
    url: "https://example.com/ml/search-ranking",
    rating: 4.8,
    relevance: 96,
    content: "Machine learning enhances search by adapting to user behavior patterns and providing personalized results."
  },
  {
    id: 7,
    title: "Vector Search and Embeddings",
    description: "Use vector embeddings for semantic similarity search beyond keyword matching.",
    snippet: "Transform text into vectors for more accurate and context-aware search results.",
    source: "Vector DB Insights",
    category: "Search Tech",
    tags: ["embeddings", "vector search", "semantic similarity"],
    url: "https://example.com/vector-search",
    rating: 4.9,
    relevance: 97,
    content: "Vector search enables finding conceptually similar content, improving upon traditional keyword-based approaches."
  },
  {
    id: 8,
    title: "Search Analytics and Insights",
    description: "Track search performance metrics and user behavior to continuously improve the search experience.",
    snippet: "Monitor query success rates, click patterns, and user satisfaction scores.",
    source: "Analytics Weekly",
    category: "Productivity",
    tags: ["analytics", "metrics", "optimization"],
    url: "https://example.com/analytics/search-insights",
    rating: 4.7,
    relevance: 90,
    content: "Search analytics provide valuable insights for optimizing algorithms and user experience design."
  },
  {
    id: 9,
    title: "Federated Search Systems",
    description: "Search across multiple disparate data sources simultaneously with unified results.",
    snippet: "Integrate search across databases, APIs, and cloud services seamlessly.",
    source: "Enterprise Tech Review",
    category: "Search Tech",
    tags: ["federated search", "data integration", "multi-source"],
    url: "https://example.com/federated-search",
    rating: 4.6,
    relevance: 88,
    content: "Federated search allows comprehensive information retrieval from diverse and distributed data sources."
  },
  {
    id: 11,
    title: "Python Data Science Fundamentals",
    description: "Master Python for data analysis, machine learning, and scientific computing with libraries like NumPy, Pandas, and Scikit-learn.",
    snippet: "Learn Python's data science ecosystem for processing, analyzing, and visualizing data.",
    source: "W3Schools Python Tutorial",
    category: "Programming",
    tags: ["python", "data science", "pandas", "numpy", "w3schools"],
    url: "https://www.w3schools.com/python/",
    rating: 4.9,
    relevance: 95,
    content: "Python has become the de facto language for data science due to its simplicity and powerful libraries for numerical computing and data manipulation. W3Schools provides comprehensive Python tutorials covering syntax, data types, functions, and advanced topics."
  },
  {
    id: 12,
    title: "Java Enterprise Development",
    description: "Build scalable enterprise applications with Java EE, Spring Framework, and microservices architecture.",
    snippet: "Develop robust backend systems using Java's enterprise-grade features and frameworks.",
    source: "W3Schools Java Tutorial",
    category: "Programming",
    tags: ["java", "enterprise", "spring", "backend", "w3schools"],
    url: "https://www.w3schools.com/java/",
    rating: 4.7,
    relevance: 92,
    content: "Java remains a cornerstone of enterprise software development, offering strong typing, performance, and extensive ecosystem support. W3Schools Java tutorial covers OOP concepts, syntax, methods, classes, and advanced Java features."
  },
  {
    id: 13,
    title: "Dart and Flutter Mobile Development",
    description: "Create cross-platform mobile applications with Dart programming language and Flutter framework.",
    snippet: "Build native iOS and Android apps from a single codebase using Dart and Flutter.",
    source: "W3Schools Dart Tutorial",
    category: "Programming",
    tags: ["dart", "flutter", "mobile", "cross-platform", "w3schools"],
    url: "https://www.w3schools.com/dart/",
    rating: 4.8,
    relevance: 94,
    content: "Dart's modern syntax and Flutter's widget-based architecture enable rapid development of beautiful, performant mobile applications. W3Schools Dart tutorial covers syntax, variables, operators, and Flutter integration."
  },
  {
    id: 14,
    title: "React JS Component Architecture",
    description: "Design scalable React applications with proper component composition, state management, and performance optimization.",
    snippet: "Master React's component lifecycle, hooks, and advanced patterns for building maintainable UIs.",
    source: "W3Schools React Tutorial",
    category: "Programming",
    tags: ["react", "javascript", "frontend", "components", "w3schools"],
    url: "https://www.w3schools.com/react/",
    rating: 4.9,
    relevance: 96,
    content: "React's component-based architecture promotes reusability, testability, and maintainability in modern web applications. W3Schools React tutorial covers JSX, components, props, state, and hooks."
  },
  {
    id: 15,
    title: "Node.js Backend Development",
    description: "Build fast, scalable server-side applications with Node.js, Express, and modern JavaScript.",
    snippet: "Create RESTful APIs, real-time applications, and microservices using Node.js ecosystem.",
    source: "W3Schools Node.js Tutorial",
    category: "Programming",
    tags: ["nodejs", "express", "backend", "api", "w3schools"],
    url: "https://www.w3schools.com/nodejs/",
    rating: 4.8,
    relevance: 93,
    content: "Node.js enables JavaScript to run on the server, allowing full-stack JavaScript development and high-performance I/O operations. W3Schools Node.js tutorial covers modules, HTTP, file system, and Express framework."
  },
  {
    id: 16,
    title: "HTML5 Semantic Web Development",
    description: "Create accessible, SEO-friendly web pages using HTML5 semantic elements and modern markup practices.",
    snippet: "Structure web content properly with semantic HTML for better accessibility and search engine optimization.",
    source: "W3Schools HTML Tutorial",
    category: "Programming",
    tags: ["html", "semantic", "accessibility", "seo", "w3schools"],
    url: "https://www.w3schools.com/html/",
    rating: 4.6,
    relevance: 88,
    content: "Semantic HTML provides meaning to web content, improving accessibility, SEO, and maintainability of web applications. W3Schools HTML tutorial covers elements, attributes, forms, and semantic markup."
  },
  {
    id: 17,
    title: "CSS Grid and Flexbox Layout",
    description: "Master modern CSS layout techniques with Grid and Flexbox for responsive, professional web designs.",
    snippet: "Create complex layouts with CSS Grid and Flexbox without relying on external frameworks.",
    source: "W3Schools CSS Tutorial",
    category: "Programming",
    tags: ["css", "grid", "flexbox", "responsive", "w3schools"],
    url: "https://www.w3schools.com/css/",
    rating: 4.8,
    relevance: 91,
    content: "CSS Grid and Flexbox provide powerful layout capabilities that enable complex, responsive designs with clean, maintainable code. W3Schools CSS tutorial covers selectors, properties, Grid, Flexbox, and responsive design."
  },
  {
    id: 18,
    title: "Modern JavaScript ES6+ Features",
    description: "Leverage advanced JavaScript features including async/await, destructuring, modules, and modern syntax.",
    snippet: "Write cleaner, more maintainable JavaScript code using ES6+ features and best practices.",
    source: "W3Schools JavaScript Tutorial",
    category: "Programming",
    tags: ["javascript", "es6", "async", "modern", "w3schools"],
    url: "https://www.w3schools.com/js/",
    rating: 4.9,
    relevance: 97,
    content: "Modern JavaScript features enable more expressive, readable, and maintainable code with better performance and developer experience. W3Schools JavaScript tutorial covers ES6+ features, async programming, and modern JavaScript best practices."
  }
];
